### ISSUE TITLE
What about deb packaging?

### ISSUE THREAD

**Issue by adomenech73** [DieterReuter/arm64-docker-builder#3]
Thanks for the great scripts!! I could compile docker 1.12.0-rc3 out of the box on pine64 with ubuntu xenial rootfs

I was thinking perhaps deb packaging could solve dependencies problem, but I'm a bit lost because existing packages have complete different binaries like docker-containerd, docker-containerd-shim or docker-runc

You know why this difference from github aarch64 source build binaries?
In my case I'm trying to upgrade actual docker 1.10.3 on xenial rootfs, for swarm test but I'm trying to understand the details

**Comment by DieterReuter** [comment]
Honestly a great idea, but there is already a build script in the docker/docker GH repo for this purpose. 

Basically you just need a running Docker engine on your build machine, then firing `make deb` to build the .deb packages for all specific aarch64 OSes.

But right now, there is still some more work to adapt it for aarch64.

**Comment by adomenech73** [comment]
I tested it now and you are totally on true, I couldn't build a complete deb package because some lost ltdl.h dependency but I've seen this is the right way to do it. Thanks

**Comment by DieterReuter** [comment]
The `make deb` already works well for ARMv6 and ARMv7. It has to be fixed for aarch64 later on, hope someone kicks in and fixes it within a few weeks or months in the upstream repo. Then it's pretty easier to build a .deb package for aarch64/ARMv8.
